[workspace]
members = ["cargo:."]

[dist]
cargo-dist-version = "0.31.0"
ci = "github"
installers = ["homebrew", "msi"]
tap = "objz/homebrew-tap"
targets = ["aarch64-apple-darwin", "aarch64-unknown-linux-gnu", "x86_64-apple-darwin", "x86_64-unknown-linux-gnu", "x86_64-pc-windows-msvc"]
install-path = "CARGO_HOME"
publish-jobs = ["homebrew", "./publish-crates", "./publish-aur", "./publish-winget"]
github-custom-job-permissions = { publish-crates = { contents = "read" }, publish-aur = { contents = "read" }, publish-winget = { contents = "read" } }
github-build-setup = "../dist-build-setup.yml"
hosting = "github"
install-updater = false
allow-dirty = ["ci", "msi"]
